include ../Makefile.cfg

all: 
	
	$(MAKE_COMMAND) -C welcome
	$(MAKE_COMMAND) -C window
	$(MAKE_COMMAND) -C sqrotate
	
clean: 
	
	$(MAKE_COMMAND) -C welcome clean
	$(MAKE_COMMAND) -C window clean
	$(MAKE_COMMAND) -C sqrotate clean

distclean: clean
